# ===============================
# CONFIGURACION DE BASE DE DATOS
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/agrotrack_db
spring.datasource.username=agrotrack_user
spring.datasource.password=agrotrack2027
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# CONFIGURACION DE HIBERNATE & JPA
# ===============================
# Dialecto especifico para soportar poligonos y puntos con PostGIS
spring.jpa.database-platform=org.hibernate.spatial.dialect.postgis.PostgisPG95Dialect

# Permite a Hibernate crear las tablas automaticamente en desarrollo (update)
spring.jpa.hibernate.ddl-auto=update

# Muestra las consultas SQL en la consola para debuggear
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# CONFIGURACION DEL SERVIDOR
# ===============================
server.port=8080
server.servlet.context-path=/api

# ===============================
# CONFIGURACION DE MINIO (STORAGE)
# ===============================
minio.url=http://localhost:9000
minio.access.key=agrotrack_admin
minio.secret.key=agrotrack2027
minio.bucket.name=agrotrack-files


# ===============================
# CONFIGURACION DEL MOTOR PYTHON Y GDAL
# ===============================
# 1. Ejecutable de Python: Busca la variable de entorno PYTHON_EXEC. Si no existe, usa "python" (el global del sistema).
#python.env.path=${PYTHON_EXEC:python}
python.env.path=D:/Tesis/Backend/AgroTrack/venv/Scripts/python.exe

# 2. Script de procesamiento: Ruta RELATIVA a la raiz del proyecto. Esto funciona en cualquier SO.
#ython.script.mappaches=scripts/MapProcessing.py
python.script.mappaches=D:/Tesis/Backend/AgroTrack/scripts/MapProcessing.py

# 3. GDAL: Busca la variable GDAL_SCRIPT_PATH. Si no existe, usa la ruta estandar de Linux en servidores.
#gdal.script.path=${GDAL_SCRIPT_PATH:/usr/bin/gdal2tiles.bat}
gdal.script.path=C:/Users/Joaco/AppData/Local/Programs/OSGeo4W/apps/gdal-dev/Scripts/gdal2tiles.py